### ISSUE TITLE
Broken System-e2e tests

### ISSUE THREAD

**Issue by AndesKrrrrrrrrrrr** [island-is/island.is#10275]
System-e2e tests are failing to start. Removing `pdfkit` as a `yarn` dependency fixes the error, but of course, fails the tests using it. The error below seems to originate from `pdfkit` and bundling?

- [ ] Find root cause of failure
- [ ] Likely failure reason: https://github.com/foliojs/pdfkit/issues/990#issuecomment-760209286
- [ ] Fix test broken test cases
- [ ] Re-enable test cases

The failure in question:
```
Current test environment: dev
Playwright args: --browser webkit smoke
[BABEL] Note: The code generator has deoptimised the styling of /dist/apps/system-e2e/src/playwright.config.js as it exceeds the max of 500KB.
Error: ENOENT: no such file or directory, open '/dist/apps/system-e2e/src/data.trie'
    at Object.openSync (node:fs:594:3)
    at Object.readFileSync (node:fs:462:35)
    at node_modules/unicode-properties/unicode-properties.cjs.js (/dist/apps/system-e2e/src/playwright.config.js:13275:35)
    at require_unicode_properties_cjs (/dist/apps/system-e2e/src/playwright.config.js:9:17)
    at node_modules/fontkit/index.js (/dist/apps/system-e2e/src/playwright.config.js:140286:35)
    at require_fontkit (/dist/apps/system-e2e/src/playwright.config.js:9:17)
    at node_modules/pdfkit/js/pdfkit.js (/dist/apps/system-e2e/src/playwright.config.js:152483:19)
    at require_pdfkit (/dist/apps/system-e2e/src/playwright.config.js:9:17)
    at Object.<anonymous> (/dist/apps/system-e2e/src/playwright.config.js:156762:29)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.A._compile (/dist/apps/system-e2e/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.t.<computed>.tu._extensions.<computed> (/dist/apps/system-e2e/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/dist/apps/system-e2e/src/data.trie'
}
	zip warning: name not matched: playwright-report
	zip warning: name not matched: src/test-results

zip error: Nothing to do! (try: zip -r -0 test-results . -i playwright-report src/test-results)
```

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
